package com.busyqa.course.functional_programming;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
