/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.busyqa.course.func_programming;

import org.junit.Test;

import com.busyqa.course.functional_programming.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
