/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.busyqa.course.func_programming;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }
}
